spring.application.name=MarketPlace
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/UniversityMarket
spring.datasource.username=postgres
spring.datasource.password=
#frontend.url=http://localhost:5173
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=

security.jwt.secret=

spring.mail.host=
spring.mail.port=
spring.mail.username=fin9track@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true